version: "3"

services:
  postgres:
    image: "postgres:13-alpine"
    hostname: "postgres"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "BasicApiComparison"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  csharp:
    build:
      context: ./dotnet/src/Api/.
      dockerfile: Dockerfile.default
    image: basicapicomparison/csharp:latest
    container_name: csharp
    ports:
      - "6000:8080"
    environment:
      ConnectionStrings__SqlConnectionString: "server=postgres;port=5432;user id=user;password=pass;database=BasicApiComparison"
      # DOTNET_gcServer: 0
    depends_on:
      - postgres
  csharp-aot:
    build:
      context: ./dotnet/src/Api/.
      dockerfile: Dockerfile.aot
    image: basicapicomparison/csharp-aot:latest
    container_name: csharp-aot
    ports:
      - "6008:8080"
    environment:
      ConnectionStrings__SqlConnectionString: "server=postgres;port=5432;user id=user;password=pass;database=BasicApiComparison"
      Stack: csharp-aot
      # DOTNET_gcServer: 0
    depends_on:
      - postgres
  csharp-r2r:
    build:
      context: ./dotnet/src/Api/.
      dockerfile: Dockerfile.r2r
    image: basicapicomparison/csharp-r2r:latest
    container_name: csharp-r2r
    ports:
      - "6001:8080"
    environment:
      ConnectionStrings__SqlConnectionString: "server=postgres;port=5432;user id=user;password=pass;database=BasicApiComparison"      
      Stack: "csharp-r2r"
    depends_on:
    - postgres
  csharp-controllers:
    build:
      context: ./dotnet/src/ApiControllers/.
    image: basicapicomparison/csharp-controllers:latest
    container_name: csharp-controllers
    ports:
      - "6010:8080"
    environment:
      ConnectionStrings__SqlConnectionString: "server=postgres;port=5432;user id=user;password=pass;database=BasicApiComparison"
      # DOTNET_gcServer: 0
    depends_on:
      - postgres
  fsharp:
    build:
      context: ./dotnet/src/ApiFSharp/.
    image: basicapicomparison/fsharp:latest
    container_name: fsharp
    ports:
      - "6002:8080"
    environment:
      ConnectionStrings__SqlConnectionString: "server=postgres;port=5432;user id=user;password=pass;database=BasicApiComparison"
    depends_on:
      - postgres
  python:
    build:
      context: ./python
    image: basicapicomparison/python:latest
    container_name: python
    ports:
      - "6003:8080"
    environment:
      DB_USER: "user"
      DB_PASS: "pass"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "BasicApiComparison"
    depends_on:
      - postgres
  node-raw:
    build:
      context: ./node/raw
    image: basicapicomparison/node-raw:latest
    container_name: node-raw
    ports:
      - "6004:8080"
    environment:
      DB_USER: "user"
      DB_PASS: "pass"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "BasicApiComparison"
    depends_on:
      - postgres
  node-express:
    build:
      context: ./node/express
    image: basicapicomparison/node-express:latest
    container_name: node-express
    ports:
      - "6005:8080"
    environment:
      DB_USER: "user"
      DB_PASS: "pass"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "BasicApiComparison"
    depends_on:
      - postgres
  go:
    build:
      context: ./go
    image: basicapicomparison/go:latest
    container_name: go
    ports:
      - "6006:8080"
    environment:
      DB_USER: "user"
      DB_PASS: "pass"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "BasicApiComparison"
    depends_on:
      - postgres
  kotlin:
    build:
      context: ./kotlin
    image: basicapicomparison/kotlin:latest
    container_name: kotlin
    ports:
      - "6007:8080"
    environment:
      DB_USER: "user"
      DB_PASS: "pass"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "BasicApiComparison"
    depends_on:
      - postgres
  rust:
    build:
      context: ./rust
    image: basicapicomparison/rust:latest
    container_name: rust
    ports:
      - "6009:8080"
    environment:
      DB_USER: "user"
      DB_PASS: "pass"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "BasicApiComparison"
    depends_on:
      - postgres