FROM mcr.microsoft.com/dotnet/aspnet:8.0-jammy-chiseled AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS build
WORKDIR /src
COPY ["dotnet/src/Api/Api.csproj", "Api/"]
RUN dotnet restore "Api/Api.csproj"
WORKDIR "/src/Api"
COPY dotnet/src/Api/. .

FROM build AS publish
RUN dotnet publish "Api.csproj" -c Release -o /app/publish /p:PublishAot=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Api.dll"]
