FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS build
ARG TARGETARCH
WORKDIR /src
COPY ["Api.csproj", "."]
RUN dotnet restore "Api.csproj" -a $TARGETARCH
COPY [".", "."]
RUN dotnet publish "Api.csproj" --no-restore -c Release -o /app /p:PublishAot=false -a $TARGETARCH

FROM mcr.microsoft.com/dotnet/aspnet:8.0-jammy-chiseled AS base
WORKDIR /app
EXPOSE 8080
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Api.dll"]
